apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestration-backend
  labels:
    app: orchestration-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestration-backend
  template:
    metadata:
      labels:
        app: orchestration-backend
    spec:
      serviceAccountName: orchestration-backend-sa
      containers:
        - name: orchestration-backend
          image: leeflangjs/orchestration-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: keycloak.auth-server-url
              value: https://login-demo.dissco.eu/auth
            - name: keycloak.realm
              value: dissco
            - name: keycloak.resource
              value: orchestration-service
            - name: token.secret
              valueFrom:
                secretKeyRef:
                  name: keycloak-client
                  key: keycloak-secret
            - name: token.id
              value: demo-api-client
            - name: token.grant-type
              value: client_credentials
            - name: endpoint.token-endpoint
              value: https://login-demo.dissco.eu/auth/realms/dissco/protocol/openid-connect/token
            - name: endpoint.handle-endpoint
              value: https://sandbox.dissco.tech/handle-manager/api/v1/pids/
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
