apiVersion: v1
kind: ServiceAccount
metadata:
  name: orchestration-backend-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: orchestration-backend-role
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [ "batch" ] # "" indicates the core API group
    resources: [ "jobs" ]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: orchestration-backend-role
  namespace: default
subjects:
  - kind: ServiceAccount
    name: orchestration-backend-sa
    namespace: default
roleRef:
  kind: Role
  name: orchestration-backend-role
  apiGroup: rbac.authorization.k8s.io
