/*
 * This file is generated by jOOQ.
 */
package eu.dissco.orchestration.backend.database.jooq;


import eu.dissco.orchestration.backend.database.jooq.tables.Handles;
import eu.dissco.orchestration.backend.database.jooq.tables.MachineAnnotationServices;
import eu.dissco.orchestration.backend.database.jooq.tables.Mapping;
import eu.dissco.orchestration.backend.database.jooq.tables.SourceSystem;
import java.util.Arrays;
import java.util.List;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Public extends SchemaImpl {

  private static final long serialVersionUID = 1L;

  /**
   * The reference instance of <code>public</code>
   */
  public static final Public PUBLIC = new Public();

  /**
   * The table <code>public.handles</code>.
   */
  public final Handles HANDLES = Handles.HANDLES;

  /**
   * The table <code>public.machine_annotation_services</code>.
   */
  public final MachineAnnotationServices MACHINE_ANNOTATION_SERVICES = MachineAnnotationServices.MACHINE_ANNOTATION_SERVICES;

  /**
   * The table <code>public.mapping</code>.
   */
  public final Mapping MAPPING = Mapping.MAPPING;

  /**
   * The table <code>public.source_system</code>.
   */
  public final SourceSystem SOURCE_SYSTEM = SourceSystem.SOURCE_SYSTEM;

  /**
   * No further instances allowed
   */
  private Public() {
    super("public", null);
  }


  @Override
  public Catalog getCatalog() {
    return DefaultCatalog.DEFAULT_CATALOG;
  }

  @Override
  public final List<Table<?>> getTables() {
    return Arrays.asList(
        Handles.HANDLES,
        MachineAnnotationServices.MACHINE_ANNOTATION_SERVICES,
        Mapping.MAPPING,
        SourceSystem.SOURCE_SYSTEM
    );
  }
}
